=== janSlopar/XML/k/xml_3.dtd
<!ELEMENT filmovi (film+)>
<!ELEMENT film (naslov, godina, redatelj)>
<!ELEMENT naslov (#PCDATA)>
<!ELEMENT godina (#PCDATA)>
<!ELEMENT redatelj (#PCDATA)>
<!ATTLIST film idFilm ID #REQUIRED>

=== janSlopar/XML/k/xml_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE filmovi SYSTEM "xml_3.dtd">
<filmovi>
    <film idFilm="f1">
        <naslov>Interstellar</naslov>
        <godina>2014</godina>
        <redatelj>Miller</redatelj>
    </film>

    <film idFilm="f2">
        <naslov>Shutter Island</naslov>
        <godina>2010</godina>
        <redatelj>netz</redatelj>
    </film>

</filmovi>
